// Golden parity tests: run the Dart `normalizeStory` over real story JSON and
// assert the output matches, item-for-item, the output of the ORIGINAL
// TypeScript `normalizeStory` (captured in test/fixtures/*.golden.json).
//
// Fixtures are generated by scratchpad gen_golden.ts, which runs the real TS
// parser. Regenerate them whenever the TS parser changes. Both sides emit the
// same canonical shape (every field explicit, null when N/A) so the comparison
// is order-independent per item and unambiguous.

import 'dart:convert';
import 'dart:io';

import 'package:flutter_test/flutter_test.dart';
import 'package:ak_reader/data/models.dart';
import 'package:ak_reader/data/parse.dart';

const _doctor = 'Doctor'; // must match gen_golden.ts

const _fixtures = [
  'level_main_00-04_beg',
  'level_act4d0_st05',
  'level_act10d5_st05',
];

// The generated goldens store the text field as the controlled-HTML string the
// TS produced (`html`/`text`). Since `parseContent` now returns structured runs,
// we compare runs on BOTH sides by parsing the golden's HTML with the SAME
// `htmlToRuns` the Dart parser uses — so parity holds without regenerating the
// fixtures, and stays robust to representation-only details (e.g. nbsp).

List<Map<String, dynamic>> _runsJson(List<TextRun> runs) =>
    [for (final r in runs) {'text': r.text, 'color': r.color}];

List<TextRun>? _itemRuns(StoryItem it) => switch (it) {
      DialogItem d => d.runs,
      NarrationItem n => n.runs,
      SubtitleItem s => s.runs,
      _ => null,
    };

Map<String, dynamic> canonActual(StoryItem it) => {
      'kind': it.kind,
      'id': it.id,
      'bg': it.bg,
      'bgImage': it.bgImage,
      'alt': it.alt,
      'branch': it.branch == null
          ? null
          : {'group': it.branch!.group, 'refs': it.branch!.refs},
      'name': it is DialogItem ? it.name : null,
      'runs': _itemRuns(it) == null ? null : _runsJson(_itemRuns(it)!),
      'portrait': it is DialogItem ? it.portrait : null,
      'options': it is DecisionItem ? it.options : null,
      'values': it is DecisionItem ? it.values : null,
      'group': it is DecisionItem ? it.group : null,
      'key': it is SoundItem ? it.key : null,
      'music': it is SoundItem ? it.music : null,
    };

Map<String, dynamic> canonGolden(Map<String, dynamic> g) {
  final htmlOrText = g['html'] ?? g['text'];
  return {
    'kind': g['kind'],
    'id': g['id'],
    'bg': g['bg'],
    'bgImage': g['bgImage'],
    'alt': g['alt'],
    'branch': g['branch'],
    'name': g['name'],
    'runs': htmlOrText == null ? null : _runsJson(htmlToRuns(htmlOrText as String)),
    'portrait': g['portrait'],
    'options': g['options'],
    'values': g['values'],
    'group': g['group'],
    'key': g['key'],
    'music': g['music'],
  };
}

List<RawLine> loadInput(String name) {
  final raw =
      jsonDecode(File('test/fixtures/$name.input.json').readAsStringSync())
          as List;
  return [
    for (var i = 0; i < raw.length; i++)
      RawLine.fromJson((raw[i] as Map).cast<String, dynamic>(), i),
  ];
}

void main() {
  group('golden parity with the TypeScript normalizeStory', () {
    for (final name in _fixtures) {
      test(name, () {
        final golden = (jsonDecode(
                File('test/fixtures/$name.golden.json').readAsStringSync())
            as List);
        final actual =
            normalizeStory(loadInput(name), _doctor).map(canonActual).toList();
        final expected = [
          for (final g in golden)
            canonGolden((g as Map).cast<String, dynamic>()),
        ];

        // Fail fast with a precise location if lengths differ.
        expect(actual.length, expected.length,
            reason: 'item count differs for $name');

        for (var i = 0; i < actual.length; i++) {
          expect(actual[i], equals(expected[i]),
              reason: 'item $i differs for $name '
                  '(kind=${actual[i]['kind']}, id=${actual[i]['id']})');
        }
      });
    }
  });
}
