// Golden parity tests: run the Dart `normalizeStory` over real story JSON and
// assert the output matches, item-for-item, the output of the ORIGINAL
// TypeScript `normalizeStory` (captured in test/fixtures/*.golden.json).
//
// Fixtures are generated by scratchpad gen_golden.ts, which runs the real TS
// parser. Regenerate them whenever the TS parser changes. Both sides emit the
// same canonical shape (every field explicit, null when N/A) so the comparison
// is order-independent per item and unambiguous.

import 'dart:convert';
import 'dart:io';

import 'package:flutter_test/flutter_test.dart';
import 'package:ak_reader/data/models.dart';
import 'package:ak_reader/data/parse.dart';

const _doctor = 'Doctor'; // must match gen_golden.ts

const _fixtures = [
  'level_main_00-04_beg',
  'level_act4d0_st05',
  'level_act10d5_st05',
];

/// Canonical map for one item — identical in shape to `canon()` in gen_golden.ts.
Map<String, dynamic> canon(StoryItem it) => {
      'kind': it.kind,
      'id': it.id,
      'bg': it.bg,
      'bgImage': it.bgImage,
      'alt': it.alt,
      'branch': it.branch == null
          ? null
          : {'group': it.branch!.group, 'refs': it.branch!.refs},
      'name': it is DialogItem ? it.name : null,
      'html': it is DialogItem
          ? it.html
          : (it is NarrationItem ? it.html : null),
      'portrait': it is DialogItem ? it.portrait : null,
      'text': it is SubtitleItem ? it.text : null,
      'options': it is DecisionItem ? it.options : null,
      'values': it is DecisionItem ? it.values : null,
      'group': it is DecisionItem ? it.group : null,
      'key': it is SoundItem ? it.key : null,
      'music': it is SoundItem ? it.music : null,
    };

List<RawLine> loadInput(String name) {
  final raw =
      jsonDecode(File('test/fixtures/$name.input.json').readAsStringSync())
          as List;
  return [
    for (var i = 0; i < raw.length; i++)
      RawLine.fromJson((raw[i] as Map).cast<String, dynamic>(), i),
  ];
}

void main() {
  group('golden parity with the TypeScript normalizeStory', () {
    for (final name in _fixtures) {
      test(name, () {
        final golden = (jsonDecode(
                File('test/fixtures/$name.golden.json').readAsStringSync())
            as List);
        final actual =
            normalizeStory(loadInput(name), _doctor).map(canon).toList();

        // Fail fast with a precise location if lengths differ.
        expect(actual.length, golden.length,
            reason: 'item count differs for $name');

        for (var i = 0; i < actual.length; i++) {
          expect(actual[i], equals(golden[i]),
              reason: 'item $i differs for $name '
                  '(kind=${actual[i]['kind']}, id=${actual[i]['id']})');
        }
      });
    }
  });
}
